// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0sZomldRsGLFsU_LJnippHBNpvfRiTZ4',
    appId: '1:596824107751:web:5de90d917c22f233d79042',
    messagingSenderId: '596824107751',
    projectId: 'neuronest-67f0d',
    authDomain: 'neuronest-67f0d.firebaseapp.com',
    storageBucket: 'neuronest-67f0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUj599ofC1t2DhMyNsBNFiT55zUbund5c',
    appId: '1:596824107751:android:fc39d8db5b2d68ded79042',
    messagingSenderId: '596824107751',
    projectId: 'neuronest-67f0d',
    storageBucket: 'neuronest-67f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzDDSUyVWayZR4C9v_QEYOSWE0qNlbbU',
    appId: '1:596824107751:ios:90ad6e2ca7deef4dd79042',
    messagingSenderId: '596824107751',
    projectId: 'neuronest-67f0d',
    storageBucket: 'neuronest-67f0d.firebasestorage.app',
    iosBundleId: 'com.example.neuronest',
  );
}
